### ISSUE TITLE
The currency "formatter" currencyStyle property is not used to format the description() String

### ISSUE THREAD

**Issue by mikezs** [danthorpe/Money#33]
The format is permanently set to ```.CurrencyStyle```

**Comment by danthorpe** [comment]
Hi @mikezs! 

`description` uses `.CurrencyStyle`. If you want to use a different formatting style, there is a function on `MoneyType` called [`formattedWithStyle(:NSNumberFormatterStyle)`](https://github.com/danthorpe/Money/blob/development/Money/Shared/Money.swift#L92).

**Comment by danthorpe** [comment]
But yes, you are correct the `formatter` static property on `CurrencyType` is not actually used directly in this function. I'll have to have a think why this was the case.

Is there a problem you are having?

**Comment by mikezs** [comment]
I have a currency that has no units (a stock exchange's points) that shouldn't be able to be displayed with it's units. I'm trying to make a new funciton called ```format()``` that honours the ```Currency```'s numberStyle

**Comment by danthorpe** [comment]
Can you share your custom `CurrencyType`?

**Comment by mikezs** [comment]
I've added an additional function to the MoneyType extension:
```/**
     
     ### Formatted String
     
     This function will format the Money type into a string for
     the current locale.
     
     For custom currencies which define their own currency code,
     create a lazy static `NSNumberFormatter`. Set the following
     properties on it: `currencySymbol`, `internationalCurrencySymbol`
     `currencyGroupingSeparator` and `currencyDecimalSeparator`, as they
     will be used when formatting the string. Feel free to fall back to
     the current locale's values for any of these to maintain
     natural looking formatting. See the example project for more.
     
     - returns: a localized and formatted string for the money amount.
     */
    func formatted() -> String {
        return Currency.formattedWithStyle(Currency.formatter.numberStyle, forLocaleId: NSLocale.currentLocale().localeIdentifier)(amount)
    }
```

and then call this in the description and it works correctly

**Comment by mikezs** [comment]
Here's an example of the problem:

```
import Money

extension Currency {
    public final class ExchangeCurrency: CustomCurrencyType {
        public static let code: String = "POINTS"
        public static let symbol: String = ""
        public static let scale: Int = 2
        public static let formatter: NSNumberFormatter = {
            let formatter = NSNumberFormatter()
            formatter.numberStyle = .DecimalStyle
            formatter.maximumFractionDigits = Currency.ExchangeCurrency.scale
            //formatter.currencySymbol = Currency.ExchangeCurrency.symbol
            return formatter
        }()
    }
}

public typealias Pts        = _Money<Currency.ExchangeCurrency>
```

With my change above it works fine.

Strangely, if you uncomment that line, you get stuck at a semaphore blocking the UI thread, with or without my change.

**Comment by danthorpe** [comment]
Okay, well, I think a simpler solution is just to implement `formattedWithStyle(:, forLocakeId:)` in your custom currency type. The [default implementation](https://github.com/danthorpe/Money/blob/development/Money/Shared/Currency.swift#L89) will only work for standard ISO currencies, but this function is what `MoneyType` calls and it is designed as part of the `CurrencyType` protocol so that custom currencies can provide their own formatting.

**Comment by danthorpe** [comment]
Have you tried setting `symbol` to `.None`? I think it's an optional.

Not seen semaphore blocking issue - can you grab a screen shot of the stack trace from Xcode?

**Comment by danthorpe** [comment]
Okay, so.. because your currency has a custom code, the default `formattedWithStyle()` function's will grab the "defaults" from the `formatter` property. So the reason for all of this is for locale support. Essentially there is a private static number formatter which is reset & configured inside `formattedWithStyle`, and if the currency code is not available in the given locale, the defaults are taken from the currency type's `formatter` property. However... I'm not actually sure how `NSNumberFormatter` works if the currency symbol is `.None` here - does it default to whatever the local currency is for your region?

**Comment by mikezs** [comment]
No, it uses the first 3 letters of the code as a prefix if using ```.None``` or just not specifying one at all

**Comment by danthorpe** [comment]
Okay, so you can get round it for now by setting the symbol to `""`, but I will fix this bug.

I'm still not quite sure why it's necessary to create a new `formatted` function and override `description` though...?

**Comment by mikezs** [comment]
Here's the semaphore problem stack trace
![screen shot 2016-01-07 at 11 44 42](https://cloud.githubusercontent.com/assets/1911467/12169928/59e1bc5a-b534-11e5-8ca2-e0ad9d3d4061.png)

**Comment by danthorpe** [comment]
Interesting okay, I'll look into that as well, thanks!

**Comment by mikezs** [comment]
I can't get around it with the blank code because of the semaphore bug :( I need to implement/override the function.

**Comment by danthorpe** [comment]
Can you configure the `formatter` in your currency type without accessing itself? i.e.

```swift
import Money

extension Currency {
    public final class ExchangeCurrency: CustomCurrencyType {
        public static let code: String = "POINTS"
        public static let symbol: String = ""
        public static let scale: Int = 2
        public static let formatter: NSNumberFormatter = {
            let formatter = NSNumberFormatter()
            formatter.numberStyle = .DecimalStyle
            formatter.maximumFractionDigits = 2
            formatter.currencySymbol = ""
            return formatter
        }()
    }
}

public typealias Pts        = _Money<Currency.ExchangeCurrency>
```

Does that still cause the semaphore bug?

**Comment by mikezs** [comment]
That fixes the bug and using .CurrencyStyle works now too

**Comment by danthorpe** [comment]
Okay, I'll refactor `CurrencyType` to remove the `formatter` property from the protocol, and get by with just the `code`, `symbol` and `scale` properties.

**Comment by danthorpe** [comment]
So, just to clarify, without the semaphore bug, it is not necessary to override `description` and implement a `formatted` function? And, `"\(pts)"` works as expected?

**Comment by mikezs** [comment]
Yes, if you want to have a custom number formatter, you'll have to override description on your custom ```Currency``` and create it there.

**Comment by danthorpe** [comment]
Okay, so `CurrencyType` should have a "standard number formatter style" which would default to `.CurrencyStyle` but in your case, you could override it to `.DecimalStyle`.

**Comment by danthorpe** [comment]
Also, just a thought, seeing as your currency type has no symbol, and formats like a decimal, it might well be easier to create your own `DecimalNumberType`, instead of `MoneyType`.

Something like this:

```swift
import Money

extension DecimalNumberBehavior {
    public struct Exchange: DecimalNumberBehaviorType {
        public static let decimalNumberBehaviors = NSDecimalNumberHandler(roundingMode: .RoundBankers, scale: 2, raiseOnExactness: false, raiseOnOverflow: false, raiseOnUnderflow: false, raiseOnDivideByZero: true)
    }
}

typealias Points = _Decimal<DecimalNumberBehavior.Exchange>
```
I haven't tried doing any formatting with this - but I think this is semantically closer to what you want, if you're just representing specific decimals?

**Comment by mikezs** [comment]
It does seem closer to what we're currently using it for. Thank you for the suggestion.

**Comment by danthorpe** [comment]
@mikezs I've got #34 done which address this issue. There is a branch: `feature/MNY-34_refactor_currency_type` which you're welcome to try. I'll be merging it into development later today.

Sorry it's taken me so long to get to this - had a bunch of other stuff pile up.
