### ISSUE TITLE
unable to init money variable with custom decimal variable

### ISSUE THREAD

**Issue by RajChanchal** [danthorpe/Money#48]
let money: GBP=34.0

this is possible

but this isn't

var myNumber:Double = 34.0
let money:GBP = myNumber

Error is cannot convert value of type Double to specified type 'GBP'

**Comment by danthorpe** [comment]
Yeah, Swift does not support automatic type casting.

For example you cannot do this either:

```swift
let aDouble: Double = 34.0
let anInteger: Int = aDouble
```

However, you can do this:

```swift
let aDouble: Double = 34.0
let anInteger = Int(aDouble)
```

And in the same way, you can also do this:

```swift
let myNumber: Double = 34.0
let money = GBP(myNumber)
```

This works for any `MoneyType`. Please re-open if you still have issues.
