### ISSUE TITLE
Able to pass NSLocale to formatter

### ISSUE THREAD

**Issue by wess** [danthorpe/Money#53]
```swift
let money: Money = 99.99
print("She has \(money.formattedWithStyle(.CurrencyPluralStyle, forLocale: .Chinese(.China)))")
```
 Ability to pass NSLocale to the ```forLocale``` param

**Comment by danthorpe** [comment]
Hi @wess - is this not already supported? https://github.com/danthorpe/Money/blob/development/Money/Shared/Money.swift#L112

**Comment by wess** [comment]
I missed that, my apologies

**Comment by danthorpe** [comment]
Sorry - you are quite right. [`Locale`](https://github.com/danthorpe/Money/blob/development/Money/Shared/Autogenerated.swift#L4623) is not `NSLocale` - this is going to be a problem for Swift 3.

We can add an extension which accepts a `NSLocale` or identifier? Ultimately it calls though into the static method on [`Currency`](https://github.com/danthorpe/Money/blob/development/Money/Shared/Currency.swift#L89).

I can't do this until the weekend - but happy to accept a Pull Request from you if you want to add a method to the same extension in Money.swift?
