### ISSUE TITLE
Getting Array of All Available Currencies

### ISSUE THREAD

**Issue by morluna** [danthorpe/Money#81]
Hello, 

I was searching through the source code trying to find a method that would return a list of all currencies. Is this possible? I'm trying to create a very simple application that allows users to be able to select currencies from a list and add them to their "preferred" currencies. 

I hope this is the right place to ask these questions, and thanks for your help!

**Comment by danthorpe** [comment]
Hi @camdendevelopers, well, the money types, are _types_, not strings, and I don't think you should want to instantiate them just to display in some UI.

What you probably want is just `Locale.isoCurrencyCodes` from `Foundation.Locale`.

**Comment by morluna** [comment]
Yes you are completely right, I closed my issue right away because of it. Thanks for you quick response!
