### ISSUE TITLE
dyld: Library not loaded: @rpath/Money.framework/Money

### ISSUE THREAD

**Issue by SubbaNelakudhiti** [danthorpe/Money#91]
Hello,

I just run a simple iOS app with Money.framework and it is crash when running with error:

dyld: Library not loaded: @rpath/Money.framework/Money
  Referenced from: /var/containers/Bundle/Application/206D71A3-3278-4DEE-8C0C-41A65C237AC4/MobileOAM.app/MobileOAM
  Reason: image not found

I don't know what image is ?

P/s: XCode 9.2, Swift4, Mac OS X 10.13.3(High Sierra)

**Comment by danthorpe** [comment]
Hello!

If you need to install CocoaPods - run `pod repo master update` to first update CocoaPods.

**Comment by SubbaNelakudhiti** [comment]
@danthorpe thanks for your earliest response. I tried, but still I'm can't able to install Money frame work into my project.

**Comment by danthorpe** [comment]
Okay. What would you like? I'm not really sure how I can help you, or what you expect here?

**Comment by SubbaNelakudhiti** [comment]
Actually, I want to install Money frame work into my project which is swift 4, can you help me the procedure.
In pod file, I mentioned as **pod 'Money'**
In terminal I used **pod repo update** and **pod install** I already have cocoa pods in my project. I'm also able to access remaining frame works except money frame work.

**Comment by danthorpe** [comment]
No - Money doesn't support Swift 4.

**Comment by SubbaNelakudhiti** [comment]
Ok, thanks @danthorpe. Do you've any plans to update this frame work.

**Comment by danthorpe** [comment]
Unfortunately I don't have enough time to spend on it. It doesn't support Swift 4.0 and there are architectural issues which are likely insurmountable in the current state.

**Comment by SubbaNelakudhiti** [comment]
@danthorpe Thank you so much for your response. I got it now.
